#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef SMARTLOOKOBJCPROXY_SWIFT_H
#define SMARTLOOKOBJCPROXY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SmartlookObjCProxy",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS_NAMED("EventTrackingObjC")
@interface SLEventTracking : NSObject
@property (nonatomic) BOOL trackUserInteraction;
@property (nonatomic) BOOL trackNavigation;
@property (nonatomic) BOOL trackRageClicks;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) SLEventTracking * _Nonnull default_;)
+ (SLEventTracking * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SLEventTracking * _Nonnull noTracking;)
+ (SLEventTracking * _Nonnull)noTracking SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


enum SLMaskType : NSInteger;

SWIFT_CLASS_NAMED("MaskElementObjc")
@interface SLMaskElement : NSObject
@property (nonatomic, readonly) CGRect rect;
@property (nonatomic, readonly) enum SLMaskType type;
- (nonnull instancetype)initWithRect:(CGRect)rect type:(enum SLMaskType)type OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM_NAMED(NSInteger, SLMaskType, "MaskType", open) {
  SLMaskTypeCovering = 0,
  SLMaskTypeErasing = 1,
};


SWIFT_CLASS_NAMED("RecordingMaskObjc")
@interface SLRecordingMask : NSObject
@property (nonatomic, copy) NSArray<SLMaskElement *> * _Nonnull elements;
- (nonnull instancetype)initWithElements:(NSArray<SLMaskElement *> * _Nonnull)elements OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM_NAMED(NSInteger, SLRenderingMode, "RenderingModeObjC", open) {
  SLRenderingModeUndefined = -1,
  SLRenderingModeNative = 0,
  SLRenderingModeWireframe = 1,
  SLRenderingModeNoRendering = 2,
};


SWIFT_CLASS_NAMED("SmartlookObjc")
@interface SmartlookObjc : NSObject
+ (void)start;
+ (void)stop;
+ (void)reset;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol SLBridgeInterface;

@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (BOOL)registerBridgeInterface:(id <SLBridgeInterface> _Nonnull)bridgeInterface SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)unregisterBridgeInterface:(id <SLBridgeInterface> _Nonnull)bridgeInterface SWIFT_WARN_UNUSED_RESULT;
@end

@class UIView;

@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (void)setViewClassSensitivityWithViewClass:(SWIFT_METATYPE(UIView) _Nonnull)viewClass isSensitive:(BOOL)isSensitive;
+ (void)setViewInstanceSensitivityWithView:(UIView * _Nonnull)view isSensitive:(BOOL)isSensitive;
+ (void)setRecordingMask:(SLRecordingMask * _Nullable)mask;
@end

@class NSString;

@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (void)trackEventWithName:(NSString * _Nonnull)name propertiesMap:(NSDictionary<NSString *, NSString *> * _Nullable)map;
+ (void)trackNavigationEnterWithName:(NSString * _Nonnull)name propertiesMap:(NSDictionary<NSString *, NSString *> * _Nullable)map;
+ (void)trackNavigationExitWithName:(NSString * _Nonnull)name propertiesMap:(NSDictionary<NSString *, NSString *> * _Nullable)map;
+ (void)trackSelectorWithName:(NSString * _Nonnull)name propertiesMap:(NSDictionary<NSString *, NSString *> * _Nullable)map;
@end

enum SLStatus : NSInteger;

@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (void)registerStatusChangeObserverWithCallback:(void (^ _Nonnull)(enum SLStatus))callback;
+ (void)unregisterStatusChangeObserver;
@end


@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (void)setEventPropertyWithName:(NSString * _Nonnull)name value:(NSString * _Nullable)value;
+ (NSString * _Nullable)getEventPropertyWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
+ (void)removeEventPropertyWithName:(NSString * _Nonnull)name;
+ (void)clearAllEventProperties;
@end


@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (void)registerRenderingModeChangeObserverWithCallback:(void (^ _Nonnull)(enum SLRenderingMode))callback;
+ (void)unregisterRenderingModeChangeObserver;
@end


@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (void)openNewSession;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable sessionUrl;)
+ (NSString * _Nullable)sessionUrl SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable sessionUrlWithTimeStamp;)
+ (NSString * _Nullable)sessionUrlWithTimeStamp SWIFT_WARN_UNUSED_RESULT;
+ (void)registerNewSessionObserverWithCallback:(void (^ _Nonnull)(NSString * _Nullable))callback;
+ (void)unregisterNewSessionObserver;
@end


@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable projectKey;)
+ (NSString * _Nullable)projectKey SWIFT_WARN_UNUSED_RESULT;
+ (void)setProjectKey:(NSString * _Nullable)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger preferredFrameRate;)
+ (NSInteger)preferredFrameRate SWIFT_WARN_UNUSED_RESULT;
+ (void)setPreferredFrameRate:(NSInteger)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum SLRenderingMode preferredRenderingMode;)
+ (enum SLRenderingMode)preferredRenderingMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setPreferredRenderingMode:(enum SLRenderingMode)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL preferredUseAdaptiveFrameRate;)
+ (BOOL)preferredUseAdaptiveFrameRate SWIFT_WARN_UNUSED_RESULT;
+ (void)setPreferredUseAdaptiveFrameRate:(BOOL)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) SLEventTracking * _Nullable preferredEventTracking;)
+ (SLEventTracking * _Nullable)preferredEventTracking SWIFT_WARN_UNUSED_RESULT;
+ (void)setPreferredEventTracking:(SLEventTracking * _Nullable)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) id _Nullable privatePreferences;)
+ (id _Nullable)privatePreferences SWIFT_WARN_UNUSED_RESULT;
+ (void)setPrivatePreferences:(id _Nullable)newValue;
@end


@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable stateProjectKey;)
+ (NSString * _Nullable)stateProjectKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) enum SLStatus stateStatus;)
+ (enum SLStatus)stateStatus SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL stateUsingStateAdaptiveFrameRate;)
+ (BOOL)stateUsingStateAdaptiveFrameRate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isRecording;)
+ (BOOL)isRecording SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger stateFrameRate;)
+ (NSInteger)stateFrameRate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) enum SLRenderingMode stateRenderingMode;)
+ (enum SLRenderingMode)stateRenderingMode SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SLEventTracking * _Nullable stateEventTracking;)
+ (SLEventTracking * _Nullable)stateEventTracking SWIFT_WARN_UNUSED_RESULT;
@end


@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (void)openNewUser;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable userIdentifier;)
+ (NSString * _Nullable)userIdentifier SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserIdentifier:(NSString * _Nullable)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable userName;)
+ (NSString * _Nullable)userName SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserName:(NSString * _Nullable)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable userEmail;)
+ (NSString * _Nullable)userEmail SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserEmail:(NSString * _Nullable)newValue;
+ (NSString * _Nullable)getUserPropertyWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserPropertyWithName:(NSString * _Nonnull)name value:(NSString * _Nullable)value;
+ (void)removeUserPropertyWithName:(NSString * _Nonnull)name;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable userUrl;)
+ (NSString * _Nullable)userUrl SWIFT_WARN_UNUSED_RESULT;
+ (void)registerNewUserObserverWithCallback:(void (^ _Nonnull)(NSString * _Nullable))callback;
+ (void)unregisterNewUserObserver;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, SLStatus, "StatusObjC", open) {
  SLStatusRecording = 0,
  SLStatusNotStarted = 1,
  SLStatusStopped = 2,
  SLStatusProjectLimitReached = 4,
  SLStatusInternalError = 6,
  SLStatusNotRunningInSwiftUIContext = 7,
  SLStatusUnsupportedPlatform = 8,
  SLStatusDiskCacheCapacityOverreached = 9,
};


@interface UIView (SWIFT_EXTENSION(SmartlookObjCProxy))
@property (nonatomic) BOOL slSensitive;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef SMARTLOOKOBJCPROXY_SWIFT_H
#define SMARTLOOKOBJCPROXY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SmartlookObjCProxy",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS_NAMED("EventTrackingObjC")
@interface SLEventTracking : NSObject
@property (nonatomic) BOOL trackUserInteraction;
@property (nonatomic) BOOL trackNavigation;
@property (nonatomic) BOOL trackRageClicks;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) SLEventTracking * _Nonnull default_;)
+ (SLEventTracking * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SLEventTracking * _Nonnull noTracking;)
+ (SLEventTracking * _Nonnull)noTracking SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


enum SLMaskType : NSInteger;

SWIFT_CLASS_NAMED("MaskElementObjc")
@interface SLMaskElement : NSObject
@property (nonatomic, readonly) CGRect rect;
@property (nonatomic, readonly) enum SLMaskType type;
- (nonnull instancetype)initWithRect:(CGRect)rect type:(enum SLMaskType)type OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM_NAMED(NSInteger, SLMaskType, "MaskType", open) {
  SLMaskTypeCovering = 0,
  SLMaskTypeErasing = 1,
};


SWIFT_CLASS_NAMED("RecordingMaskObjc")
@interface SLRecordingMask : NSObject
@property (nonatomic, copy) NSArray<SLMaskElement *> * _Nonnull elements;
- (nonnull instancetype)initWithElements:(NSArray<SLMaskElement *> * _Nonnull)elements OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM_NAMED(NSInteger, SLRenderingMode, "RenderingModeObjC", open) {
  SLRenderingModeUndefined = -1,
  SLRenderingModeNative = 0,
  SLRenderingModeWireframe = 1,
  SLRenderingModeNoRendering = 2,
};


SWIFT_CLASS_NAMED("SmartlookObjc")
@interface SmartlookObjc : NSObject
+ (void)start;
+ (void)stop;
+ (void)reset;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol SLBridgeInterface;

@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (BOOL)registerBridgeInterface:(id <SLBridgeInterface> _Nonnull)bridgeInterface SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)unregisterBridgeInterface:(id <SLBridgeInterface> _Nonnull)bridgeInterface SWIFT_WARN_UNUSED_RESULT;
@end

@class UIView;

@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (void)setViewClassSensitivityWithViewClass:(SWIFT_METATYPE(UIView) _Nonnull)viewClass isSensitive:(BOOL)isSensitive;
+ (void)setViewInstanceSensitivityWithView:(UIView * _Nonnull)view isSensitive:(BOOL)isSensitive;
+ (void)setRecordingMask:(SLRecordingMask * _Nullable)mask;
@end

@class NSString;

@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (void)trackEventWithName:(NSString * _Nonnull)name propertiesMap:(NSDictionary<NSString *, NSString *> * _Nullable)map;
+ (void)trackNavigationEnterWithName:(NSString * _Nonnull)name propertiesMap:(NSDictionary<NSString *, NSString *> * _Nullable)map;
+ (void)trackNavigationExitWithName:(NSString * _Nonnull)name propertiesMap:(NSDictionary<NSString *, NSString *> * _Nullable)map;
+ (void)trackSelectorWithName:(NSString * _Nonnull)name propertiesMap:(NSDictionary<NSString *, NSString *> * _Nullable)map;
@end

enum SLStatus : NSInteger;

@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (void)registerStatusChangeObserverWithCallback:(void (^ _Nonnull)(enum SLStatus))callback;
+ (void)unregisterStatusChangeObserver;
@end


@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (void)setEventPropertyWithName:(NSString * _Nonnull)name value:(NSString * _Nullable)value;
+ (NSString * _Nullable)getEventPropertyWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
+ (void)removeEventPropertyWithName:(NSString * _Nonnull)name;
+ (void)clearAllEventProperties;
@end


@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (void)registerRenderingModeChangeObserverWithCallback:(void (^ _Nonnull)(enum SLRenderingMode))callback;
+ (void)unregisterRenderingModeChangeObserver;
@end


@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (void)openNewSession;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable sessionUrl;)
+ (NSString * _Nullable)sessionUrl SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable sessionUrlWithTimeStamp;)
+ (NSString * _Nullable)sessionUrlWithTimeStamp SWIFT_WARN_UNUSED_RESULT;
+ (void)registerNewSessionObserverWithCallback:(void (^ _Nonnull)(NSString * _Nullable))callback;
+ (void)unregisterNewSessionObserver;
@end


@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable projectKey;)
+ (NSString * _Nullable)projectKey SWIFT_WARN_UNUSED_RESULT;
+ (void)setProjectKey:(NSString * _Nullable)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger preferredFrameRate;)
+ (NSInteger)preferredFrameRate SWIFT_WARN_UNUSED_RESULT;
+ (void)setPreferredFrameRate:(NSInteger)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum SLRenderingMode preferredRenderingMode;)
+ (enum SLRenderingMode)preferredRenderingMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setPreferredRenderingMode:(enum SLRenderingMode)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL preferredUseAdaptiveFrameRate;)
+ (BOOL)preferredUseAdaptiveFrameRate SWIFT_WARN_UNUSED_RESULT;
+ (void)setPreferredUseAdaptiveFrameRate:(BOOL)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) SLEventTracking * _Nullable preferredEventTracking;)
+ (SLEventTracking * _Nullable)preferredEventTracking SWIFT_WARN_UNUSED_RESULT;
+ (void)setPreferredEventTracking:(SLEventTracking * _Nullable)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) id _Nullable privatePreferences;)
+ (id _Nullable)privatePreferences SWIFT_WARN_UNUSED_RESULT;
+ (void)setPrivatePreferences:(id _Nullable)newValue;
@end


@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable stateProjectKey;)
+ (NSString * _Nullable)stateProjectKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) enum SLStatus stateStatus;)
+ (enum SLStatus)stateStatus SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL stateUsingStateAdaptiveFrameRate;)
+ (BOOL)stateUsingStateAdaptiveFrameRate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isRecording;)
+ (BOOL)isRecording SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger stateFrameRate;)
+ (NSInteger)stateFrameRate SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) enum SLRenderingMode stateRenderingMode;)
+ (enum SLRenderingMode)stateRenderingMode SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SLEventTracking * _Nullable stateEventTracking;)
+ (SLEventTracking * _Nullable)stateEventTracking SWIFT_WARN_UNUSED_RESULT;
@end


@interface SmartlookObjc (SWIFT_EXTENSION(SmartlookObjCProxy))
+ (void)openNewUser;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable userIdentifier;)
+ (NSString * _Nullable)userIdentifier SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserIdentifier:(NSString * _Nullable)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable userName;)
+ (NSString * _Nullable)userName SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserName:(NSString * _Nullable)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable userEmail;)
+ (NSString * _Nullable)userEmail SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserEmail:(NSString * _Nullable)newValue;
+ (NSString * _Nullable)getUserPropertyWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserPropertyWithName:(NSString * _Nonnull)name value:(NSString * _Nullable)value;
+ (void)removeUserPropertyWithName:(NSString * _Nonnull)name;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable userUrl;)
+ (NSString * _Nullable)userUrl SWIFT_WARN_UNUSED_RESULT;
+ (void)registerNewUserObserverWithCallback:(void (^ _Nonnull)(NSString * _Nullable))callback;
+ (void)unregisterNewUserObserver;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, SLStatus, "StatusObjC", open) {
  SLStatusRecording = 0,
  SLStatusNotStarted = 1,
  SLStatusStopped = 2,
  SLStatusProjectLimitReached = 4,
  SLStatusInternalError = 6,
  SLStatusNotRunningInSwiftUIContext = 7,
  SLStatusUnsupportedPlatform = 8,
  SLStatusDiskCacheCapacityOverreached = 9,
};


@interface UIView (SWIFT_EXTENSION(SmartlookObjCProxy))
@property (nonatomic) BOOL slSensitive;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
